// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
// Or manually add declarations below
interface CloudflareBindings {
  // D1 Bindings
  DB: D1Database;

  // KV Bindings
  CACHE: KVNamespace;
  TAG_VECTORS_KV: KVNamespace;

  // Vars (defined in wrangler.toml [vars])
  VECTOR_URL: string;

  // Secrets (set via `wrangler secret put`)
  VECTOR_TOKEN: string;
  X_APP_KEY: string;
  OPENAI_API_KEY: string;
}
