name = "lumin"
main = "src/index.ts"
compatibility_date = "2025-02-24" # Today's date
workers_dev = true 
account_id = "0095f5e80c93e8252a4019ae095d6848"

# Observability (logs, traces in dashboard)
[observability]
enabled = true

# D1 Database binding for edge SQLite
[[d1_databases]]
binding = "DB"
database_name = "lumin-db"
database_id = "your-d1-namespace-id"

[[kv_namespaces]]
binding = "CACHE"
id = "your_kv_namespace_id"

[vars]
VECTOR_URL = ""
VECTOR_TOKEN = ""
X_APP_KEY = ""
OPENAI_API_KEY = ""